### ISSUE TITLE
About HealthQA dataset

### ISSUE THREAD

**Issue by xumingying0612** [mingzhu0527/HAR#3]
Could you please provide the HealthQA dataset to run the code? Thank you!

**Comment by mingzhu0527** [comment]
Please email me for the dataset

**Comment by xumingying0612** [comment]
Hi I have email you( mingzhu@vt.edu ) for the dataset. Looking forward to your reply. Thank you!

**Comment by mingzhu0527** [comment]
I have shared the dataset with you

**Comment by sherrybbalonso** [comment]
Would you mind sharing the datasets with us to run code? Thanks very much!

**Comment by amithbhat1** [comment]
Hello ma'am, I have emailed you for the HeathQA dataset.... looking forward to your reply, thanks!
